### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by sarah-weatherbee** [nss-evening-cohort-9/nutshell-pistachio#17]
## User Story
As a developer, I should have created an expected layout of how our Nutshell-pistachio project should look. 

## Acceptance Criteria
I should design the layout, 
And use this as a baseline for design.

## Development 
> This will be created using Moqup.

**Comment by Lakiajo** [comment]
<img width="505" alt="Screen Shot 2019-06-05 at 5 53 48 PM" src="https://user-images.githubusercontent.com/25693669/58998468-7e139e00-87c6-11e9-8dff-a8e918d414bf.png">
